#!/usr/bin/env bash
# record-mobile-e2e.sh
# Run each Maestro flow and capture an iOS Simulator screen recording.
# Uploads recordings to a GitHub Release when GH_TOKEN is set.
#
# Prerequisites:
#   - iOS Simulator booted with Fitsy app installed
#   - Maestro CLI on PATH  (curl -Ls "https://get.maestro.mobile.dev" | bash)
#   - gh CLI on PATH and authenticated (for upload step)
#
# Usage:
#   bash scripts/record-mobile-e2e.sh [--release-tag <tag>]

set -euo pipefail

RELEASE_TAG="${RELEASE_TAG:-e2e-mobile-sprint7}"
OUT_DIR="recordings"
REPO="dgmolla/fitsy"

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --release-tag) RELEASE_TAG="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

mkdir -p "$OUT_DIR"

declare -A FLOWS=(
  ["fitsy-onboarding"]="e2e/flows/onboarding.yaml"
  ["fitsy-search"]="e2e/flows/search.yaml"
  ["fitsy-restaurant-detail"]="e2e/flows/restaurant-detail.yaml"
)

# Ordered list so output is predictable
FLOW_ORDER=("fitsy-onboarding" "fitsy-search" "fitsy-restaurant-detail")

FAILED_FLOWS=()

record_flow() {
  local name="$1"
  local flow_file="$2"
  local out_file="$OUT_DIR/${name}.mp4"

  echo ""
  echo "=== Recording: $name ==="
  echo "    Flow:   $flow_file"
  echo "    Output: $out_file"

  # Remove stale file from a prior run
  rm -f "$out_file"

  # Start simulator screen recording in background.
  # SIGINT (kill -2) triggers a clean shutdown that flushes the moov atom.
  xcrun simctl io booted recordVideo --codec h264 "$out_file" &
  RECORDER_PID=$!

  # Small delay so the recorder is fully started before Maestro drives UI
  sleep 1

  # Run the Maestro flow
  local maestro_exit=0
  maestro test "$flow_file" || maestro_exit=$?

  # Stop recorder cleanly regardless of Maestro exit code
  kill -2 "$RECORDER_PID" 2>/dev/null || true
  wait "$RECORDER_PID" 2>/dev/null || true

  if [[ $maestro_exit -ne 0 ]]; then
    echo "    [WARN] Maestro exited with code $maestro_exit for $name"
    FAILED_FLOWS+=("$name")
  else
    echo "    [OK]  $out_file"
  fi
}

for name in "${FLOW_ORDER[@]}"; do
  record_flow "$name" "${FLOWS[$name]}"
done

echo ""
echo "=== Recordings complete ==="
ls -lh "$OUT_DIR/"*.mp4 2>/dev/null || echo "(no mp4 files produced)"

# Upload to GitHub Release if gh is available and GH_TOKEN is set
if command -v gh &>/dev/null && [[ -n "${GH_TOKEN:-}" ]]; then
  echo ""
  echo "=== Uploading to GitHub Release: $RELEASE_TAG ==="

  # Create release if it doesn't exist (idempotent)
  if ! gh release view "$RELEASE_TAG" --repo "$REPO" &>/dev/null; then
    gh release create "$RELEASE_TAG" \
      --repo "$REPO" \
      --prerelease \
      --title "Mobile E2E Recordings — Sprint 7" \
      --notes "iOS Simulator recordings for Maestro E2E flows. Generated by \`scripts/record-mobile-e2e.sh\`."
  fi

  for name in "${FLOW_ORDER[@]}"; do
    local_file="$OUT_DIR/${name}.mp4"
    if [[ -f "$local_file" ]]; then
      gh release upload "$RELEASE_TAG" "$local_file" \
        --repo "$REPO" \
        --clobber
      echo "    Uploaded: $local_file"
    fi
  done

  echo ""
  echo "=== Recording URLs (paste into PR description) ==="
  for name in "${FLOW_ORDER[@]}"; do
    echo "- **${name}**: https://github.com/${REPO}/releases/download/${RELEASE_TAG}/${name}.mp4"
  done
else
  echo ""
  echo "=== Skipping upload (gh not found or GH_TOKEN not set) ==="
  echo "To upload manually:"
  echo "  export GH_TOKEN=<your-token>"
  echo "  bash scripts/record-mobile-e2e.sh"
fi

if [[ ${#FAILED_FLOWS[@]} -gt 0 ]]; then
  echo ""
  echo "=== Failed flows ==="
  for f in "${FAILED_FLOWS[@]}"; do
    echo "  - $f"
  done
  echo "Recordings may still be viewable — check $OUT_DIR/"
  exit 1
fi
