#!/usr/bin/env bash
# Point local dev at the dev environment using Vercel's Preview env as the
# single source of truth.
#
#   apps/api/.env.local                 <- vercel env pull (development)
#   apps/mobile/.env.development.local  <- EXPO_PUBLIC_* derived from the same
#   .env.dev (repo root, gitignored)    <- for scripts/dev/*.ts and dev-drift
#
# Expo loads .env.development.local ahead of .env/.env.local in dev mode, so
# production values in apps/mobile/.env stay untouched for release builds.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

DEV_API_URL="${DEV_API_URL:-https://fitsy-git-dev-dawits-projects-74b6e00f.vercel.app}"

vercel env pull --environment=development apps/api/.env.local --yes >/dev/null
vercel env pull --environment=preview .env.dev --yes >/dev/null

val() { grep -E "^$1=" .env.dev | head -1 | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//'; }
SUPA_URL="$(val SUPABASE_URL)"; SUPA_ANON="$(val SUPABASE_ANON_KEY)"
if [[ "$SUPA_URL" == *zaxkmjqozvmbifiwbxps* ]]; then
  echo "[write-local-env] Preview env still points at PRODUCTION Supabase. Run scripts/dev/provision-supabase.sh first." >&2
  exit 1
fi

cat > apps/mobile/.env.development.local <<EOF
# Generated by scripts/dev/write-local-env.sh - dev environment. Do not commit.
EXPO_PUBLIC_API_URL=${DEV_API_URL}
EXPO_PUBLIC_SUPABASE_URL=${SUPA_URL}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${SUPA_ANON}
EOF
echo "[write-local-env] wrote apps/api/.env.local (development), .env.dev (preview), apps/mobile/.env.development.local (API=${DEV_API_URL})" >&2
